interface ZIF_GJB_DISPLAY
  public .


  methods DISPLAY DEFAULT IGNORE
    importing
      !IV_INPUT type DATA OPTIONAL.
  methods DISPLAY_TABLE DEFAULT IGNORE
    IMPORTING
      !IV_INPUT TYPE DATA OPTIONAL.
  METHODS DISPLAY_MESSAGE DEFAULT IGNORE
     IMPORTING
      !IV_INPUT TYPE DATA OPTIONAL.
endinterface.
